#!/usr/bin/env bash
# Bash (init) script 11-manage_my_process that manages manage_my_process. (both files need to be pushed to git)

start () {
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
}

stop () {
    pkill -f "./manage_my_process"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
}

restart () {
    pkill -f "./manage_my_process"    
    rm /var/run/my_process.pid
    ./manage_my_process &
    echo $! >> /var/run/my_process.pid
    echo "manage_my_process restarted"
}

case "$1" in
   start) start ;;
   stop)  stop;;
   restart) restart;;
   *) echo "Usage: manage_my_process {start|stop|restart}"
      
      ;;
esac
